% 
% cases={...
%     'Combined_direct_dorsal_memory_comparison',...
%     'Curius_direct_saccades_dorsal',...
%     'Linus_direct_saccades_dorsal',...
%     'Combined_direct_dorsal',...
%     'Curius_memory_saccades_dorsal',...
%     'Linus_memory_saccades_dorsal',...
%     'Combined_memory_dorsal',...
%     'Curius_direct_saccades_ventral_shallow',...
%     'Curius_direct_saccades_ventral_medium_deep',...
%     'Curius_direct_saccades_ventral_very_deep',...
%     'Linus_direct_saccades_ventral_shallow',...
%     'Linus_direct_saccades_ventral_medium_deep',...
%     'Linus_direct_saccades_ventral_very_deep',...
%     'Combined_direct_ventral_shallow',...
%     'Combined_direct_ventral_medium_deep',...
%     'Combined_direct_ventral_very_deep',...
%     'Curius_memory_saccades_ventral_shallow',...
%     'Linus_memory_saccades_ventral_shallow',...
%     'Linus_memory_saccades_ventral_medium_deep',...
%     'Combined_memory_ventral_shallow',...
%     'Curius_direct_outside',...
%     'Combined_direct_outside',...
%     'Linus_direct_outside',...
%     'Combined_direct_dorsal_earlier_windows'...
%     }; 

% % 
% cases={...
%     'Shorter_duration_100ms',...
%     'Shorter_duration_150ms',...
%     'Shorter_duration_control',...
%     }; 
% % 
% cases={...
%     'Combined_memory_dorsal',...
%     }; 

% cases={...
%     'Combined_direct_dorsal',...
%     }; 
% cases={...
%     'Combined_direct_dorsal',...
%     'Curius_direct_saccades_dorsal',...
%     'Linus_direct_saccades_dorsal',...
%     }; 

% cases={...
%     'Combined_direct_dorsal',...
%     }; 

% cases={...
%     'Combined_direct_outside',...
%     'Combined_direct_dorsal',...
%     'Combined_direct_ventral_shallow',...
%     'Combined_direct_ventral_medium_deep',...
%     'Combined_direct_ventral_very_deep',...
%     }; 


% cases={...
%     'Curius_memory_saccades_dorsal',...
%     'Linus_memory_saccades_dorsal',...
%     'Curius_direct_saccades_dorsal',...
%     'Linus_direct_saccades_dorsal',...
%     }; 

% cases={...
%     'Combined_memory_dorsal',...
%     'Combined_direct_dorsal',...
%     }; 

% 
% cases={...
%     'Curius_memory_saccades_dorsal',...
%     'Linus_memory_saccades_dorsal',...
%     }; 

cases={...
    'Curius_direct_saccades_dorsal',...
    'Linus_direct_saccades_dorsal',...
    }; 


% cases={...
%     'Curius_memory_saccades_dorsal',...
%     'Linus_memory_saccades_dorsal',...
%     'Combined_memory_dorsal',...
%     }; 

%%% NOt existing:
%%% 'Linus_memory_saccades_ventral_very_deep','Curius_memory_saccades_ventral_medium_deep', 'Combined_memory_ventral_very_deep',...
% for i=1:numel(cases)
%     bias_and_rt_microstim(cases{i})
%    % close all;clc;
% end

bias_and_rt_microstim_Cornelius('TestCornelius')
% cases={'Linus_direct_saccades_dorsal','Linus_direct_saccades_ventral_shallow','Linus_direct_saccades_ventral_deep','Linus_direct_saccades_ventral_medium_deep'...
%     ,'Linus_direct_saccades_ventral_very_deep','Linus_memory_saccades_dorsal','Linus_memory_saccades_ventral_shallow','Linus_memory_saccades_ventral_deep',...
%     'Curius_direct_saccades_dorsal', 'Curius_direct_saccades_ventral_shallow','Curius_direct_saccades_ventral_deep','Curius_memory_saccades_dorsal',...
%     'Curius_memory_saccades_ventral_shallow','Curius_memory_saccades_ventral_deep','Combined_memory_dorsal','Combined_memory_ventral_shallow','Combined_memory_ventral_deep',...
%     'Combined_direct_dorsal','Combined_direct_ventral_shallow','Combined_direct_ventral_deep','Combined_direct_dorsal_earlier_windows','Combined_direct_outside','Curius_direct_outside','Linus_direct_outside'};
